apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-haproxy-config
  namespace: kafka
data:
  haproxy.cfg: |
    defaults
      mode tcp
      timeout connect 5s
      timeout client  1m
      timeout server  1m

    frontend clickhouse_native
      bind *:25650
      default_backend clickhouse_native_backend

    backend clickhouse_native_backend
      server clickhouse digitaldc-clickhouse-hul-samadhan.l.aivencloud.com:25650 check

    frontend clickhouse_https
      bind *:25651
      mode tcp
      default_backend clickhouse_https_backend

    backend clickhouse_https_backend
      mode tcp
      server clickhouse digitaldc-clickhouse-hul-samadhan.l.aivencloud.com:25651 check

    frontend clickhouse_mysql
      bind *:25652
      mode tcp
      default_backend clickhouse_mysql_backend

    backend clickhouse_mysql_backend
      mode tcp
      server clickhouse digitaldc-clickhouse-hul-samadhan.l.aivencloud.com:25652 check
    
    frontend starrocks_mysql
      bind *:9030
      mode tcp
      default_backend starrocks_mysql_backend

    backend starrocks_mysql_backend
      mode tcp
      server starrocks kube-starrocks-fe-service.starrocks:9030 check
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-tcp-proxy
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-tcp-proxy
  template:
    metadata:
      labels:
        app: clickhouse-tcp-proxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:latest
          ports:
            - containerPort: 25650
            - containerPort: 25651
            - containerPort: 25652
            - containerPort: 9030
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: config
          configMap:
            name: clickhouse-haproxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-proxy-svc
  namespace: kafka
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 25650
      protocol: TCP
      name: clickhouse
    - port: 25650
      targetPort: 25650
      protocol: TCP
      name: clickhouse-native
    - port: 25651
      targetPort: 25651
      protocol: TCP
      name: clickhouse-https
    - port: 25652
      targetPort: 25652
      protocol: TCP
      name: clickhouse-mysql
    - port: 9030
      targetPort: 9030
      protocol: TCP
      name: starrocks-mysql
  selector:
    app: clickhouse-tcp-proxy
