apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-haproxy-config
  namespace: kafka
data:
  haproxy.cfg: |
    defaults
      mode tcp
      timeout connect 5s
      timeout client  1m
      timeout server  1m

    frontend clickhouse_native
      bind *:25650
      default_backend clickhouse_native_backend

    backend clickhouse_native_backend
      server clickhouse samadhan-clickhouse-hul-samadhan.f.aivencloud.com:25650 check

    frontend clickhouse_https
      bind *:25651
      mode tcp
      default_backend clickhouse_https_backend

    backend clickhouse_https_backend
      mode tcp
      server clickhouse samadhan-clickhouse-hul-samadhan.f.aivencloud.com:25651 check
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-tcp-proxy
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-tcp-proxy
  template:
    metadata:
      labels:
        app: clickhouse-tcp-proxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:latest
          ports:
            - containerPort: 25650
            - containerPort: 25651
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: config
          configMap:
            name: clickhouse-haproxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-proxy-svc
  namespace: kafka
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 25650
      protocol: TCP
      name: clickhouse
    - port: 25650
      targetPort: 25650
      protocol: TCP
      name: clickhouse-native
    - port: 25651
      targetPort: 25651
      protocol: TCP
      name: clickhouse-https
  selector:
    app: clickhouse-tcp-proxy
