apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-haproxy-config
  namespace: kafka
data:
  haproxy.cfg: |
    defaults
      mode tcp
      timeout connect 5s
      timeout client  1m
      timeout server  1m

    frontend clickhouse_native
      bind *:22154
      default_backend clickhouse_native_backend

    backend clickhouse_native_backend
      server clickhouse nestle-prod-clickhouse-stackbox.l.aivencloud.com:22154 check

    frontend clickhouse_https
      bind *:22155
      mode tcp
      default_backend clickhouse_https_backend

    backend clickhouse_https_backend
      mode tcp
      server clickhouse nestle-prod-clickhouse-stackbox.l.aivencloud.com:22155 check
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-tcp-proxy
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-tcp-proxy
  template:
    metadata:
      labels:
        app: clickhouse-tcp-proxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:latest
          ports:
            - containerPort: 22154
            - containerPort: 22155
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
      volumes:
        - name: config
          configMap:
            name: clickhouse-haproxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-proxy-svc
  namespace: kafka
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 22154
      protocol: TCP
      name: clickhouse
    - port: 22154
      targetPort: 22154
      protocol: TCP
      name: clickhouse-native
    - port: 22155
      targetPort: 22155
      protocol: TCP
      name: clickhouse-https
  selector:
    app: clickhouse-tcp-proxy
